### ISSUE TITLE
Wrong parameters for working directory and doxyfile

### ISSUE THREAD

**Issue by Nanogamer7** [AgarwalSaurav/ghaction-doxygen-ghpages#1]
When attempting to deploy, the action incorrectly parses `/workspace` as the working directory and `.` as the Doxyfile. This appears to be happening due to `/workspace` being added to the docker run command (see log excerpt below) and thus being parsed as a parameter. A similar thing might be happening in this repository, as there is a double space `  ` at that location in the logs (see line 11 in [Action Doxygen and GitHub Pages](https://github.com/AgarwalSaurav/ghaction-doxygen-ghpages/actions/runs/8221259523/job/22481416900), right after `ghcr.io/agarwalsaurav/doxygen-arch:latest`), which indicate the same string is incorrectly added, but empty in this case

Copied from https://github.com/VEGO-Engine/Engine/actions/runs/8717958280/job/23914188673:
```
Run docker run --rm -v /home/runner/work/Engine/Engine/.:/workspace ghcr.io/agarwalsaurav/doxygen-arch:latest /workspace "." "Doxyfile" "docs/html"
...
Doxygen will be executed in the following directory: /workspace
Doxyfile path: .
File . could not be found!
```

**Comment by AgarwalSaurav** [comment]
Looks like you are using v2.0.0 instead of the latest v2.0.1. I guess this happened because the README was not updated. Thanks.
